apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardapi
spec:
  replicas: 4
  selector:
    matchLabels:
      api: spring
  template:
    metadata:
      labels:
        api: spring
        app: boardapi
    spec:
      containers:
        - name: board-api
          image: 192.168.40.200:57777/board-api/spring:1.0.6
          ports:
            - containerPort: 8101
