apiVersion: v1
kind: Service
metadata:
  name: boarddb-svc
spec:
  selector:
    db: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: webboard-svc
spec:
  selector:
    api: spring
  ports:
    - protocol: TCP
      port: 8101
      targetPort: 8101

