apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlistapi
spec:
  replicas: 3
  selector:
    matchLabels:
      api: fastapi
  template:
    metadata:
      labels:
        api: fastapi
    spec:
      containers:
        - name: playlistapi
          image: 192.168.40.200:57777/playlist-api/fastapi:latest
          ports:
            - containerPort: 8102
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-playlist-db
                  key: rootpasswd
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: secret-playlist-db
                  key: databasename
