apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 3  # 배포할 파드의 개수
  selector:
    matchLabels:
      web: react
  template:
    metadata:
      labels:
        web: react
    spec:
      containers:
        - name: webserver
          image: 192.168.40.200:57777/web-server/react:latest  # 이미지 이름과 태그
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    web: react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30300
  externalTrafficPolicy: Local
  type: NodePort  # 외부에서 접근 가능한 서비스 유형
